### ISSUE TITLE
Device image link broken

### ISSUE THREAD

**Issue by zerone91** [DigiRL-agent/digirl#9] opened 2024-07-24 06:36 UTC
The AVD device image link in the  env_setup/README.md is broken.

**Comment by BiEchi** [comment] 2024-07-24 16:07
It works on my end - would you please try it again?
https://drive.google.com/drive/folders/1ZGKrWiSoGqg8_NoIGT7rWmiZ8CXToaBF?usp=sharing

**Comment by zerone91** [comment] 2024-07-25 01:46
Sorry, It seems like a problem of my office network, now it's fine, thank you~

**Comment by BiEchi** [comment] 2024-07-25 02:52
Closed as the issue is solved.

**Closed as completed by BiEchi** 2024-07-25 02:52 UTC
