### ISSUE TITLE
Errors in loading model from checkpoint

### ISSUE THREAD

**Issue by tlc4418** [DigiRL-agent/digirl#16] opened 2024-08-30 16:36 UTC
Hi, I had the same issue as @mousewu in Issue #11 , where there were dimensions errors (when loading [this](https://huggingface.co/JackBAI/webshop-off2on-digirl) checkpoint). 

Doing as suggested in the issue and adding the information to the config.json fixed this problem and I managed to load the model. However, I now get the following warnings about both unused and missing weights:

```
Some weights of the model checkpoint at JackBAI/webshop-off2on-digirl were not used when initializing T5ForMultimodalGeneration: ['decoder.block.0.layer.2.DenseReluDense.wi_0.weight', 'decoder.block.0.layer.2.DenseReluDense.wi_1.weight', 'decoder.block.1.layer.2.DenseReluDense.wi_0.weight', 'decoder.block.1.layer.2.DenseReluDense.wi_1.weight', 'decoder.block.10.layer.0.SelfAttention.k.weight', 'decoder.block.10.layer.0.SelfAttention.o.weight', 'decoder.block.10.layer.0.SelfAttention.q.weight', 'decoder.block.10.layer.0.SelfAttention.v.weight', 'decoder.block.10.layer.0.layer_norm.weight', 'decoder.block.10.layer.1.EncDecAttention.k.weight', 'decoder.block.10.layer.1.EncDecAttention.o.weight', 'decoder.block.10.layer.1.EncDecAttention.q.weight', 'decoder.block.10.layer.1.EncDecAttention.v.weight', 'decoder.block.10.layer.1.layer_norm.weight', 'decoder.block.10.layer.2.DenseReluDense.wi_0.weight', 'decoder.block.10.layer.2.DenseReluDense.wi_1.weight', 'decoder.block.10.layer.2.DenseReluDense.wo.weight', 'decoder.block.10.layer.2.layer_norm.weight', 'decoder.block.11.layer.0.SelfAttention.k.weight', 'decoder.block.11.layer.0.SelfAttention.o.weight', 'decoder.block.11.layer.0.SelfAttention.q.weight', 'decoder.block.11.layer.0.SelfAttention.v.weight', 'decoder.block.11.layer.0.layer_norm.weight', 'decoder.block.11.layer.1.EncDecAttention.k.weight', 'decoder.block.11.layer.1.EncDecAttention.o.weight', 'decoder.block.11.layer.1.EncDecAttention.q.weight', 'decoder.block.11.layer.1.EncDecAttention.v.weight', 'decoder.block.11.layer.1.layer_norm.weight', 'decoder.block.11.layer.2.DenseReluDense.wi_0.weight', 'decoder.block.11.layer.2.DenseReluDense.wi_1.weight', 'decoder.block.11.layer.2.DenseReluDense.wo.weight', 'decoder.block.11.layer.2.layer_norm.weight', 'decoder.block.2.layer.2.DenseReluDense.wi_0.weight', 'decoder.block.2.layer.2.DenseReluDense.wi_1.weight', 'decoder.block.3.layer.2.DenseReluDense.wi_0.weight', 'decoder.block.3.layer.2.DenseReluDense.wi_1.weight', 'decoder.block.4.layer.2.DenseReluDense.wi_0.weight', 'decoder.block.4.layer.2.DenseReluDense.wi_1.weight', 'decoder.block.5.layer.2.DenseReluDense.wi_0.weight', 'decoder.block.5.layer.2.DenseReluDense.wi_1.weight', 'decoder.block.6.layer.0.SelfAttention.k.weight', 'decoder.block.6.layer.0.SelfAttention.o.weight', 'decoder.block.6.layer.0.SelfAttention.q.weight', 'decoder.block.6.layer.0.SelfAttention.v.weight', 'decoder.block.6.layer.0.layer_norm.weight', 'decoder.block.6.layer.1.EncDecAttention.k.weight', 'decoder.block.6.layer.1.EncDecAttention.o.weight', 'decoder.block.6.layer.1.EncDecAttention.q.weight', 'decoder.block.6.layer.1.EncDecAttention.v.weight', 'decoder.block.6.layer.1.layer_norm.weight', 'decoder.block.6.layer.2.DenseReluDense.wi_0.weight', 'decoder.block.6.layer.2.DenseReluDense.wi_1.weight', 'decoder.block.6.layer.2.DenseReluDense.wo.weight', 'decoder.block.6.layer.2.layer_norm.weight', 'decoder.block.7.layer.0.SelfAttention.k.weight', 'decoder.block.7.layer.0.SelfAttention.o.weight', 'decoder.block.7.layer.0.SelfAttention.q.weight', 'decoder.block.7.layer.0.SelfAttention.v.weight', 'decoder.block.7.layer.0.layer_norm.weight', 'decoder.block.7.layer.1.EncDecAttention.k.weight', 'decoder.block.7.layer.1.EncDecAttention.o.weight', 'decoder.block.7.layer.1.EncDecAttention.q.weight', 'decoder.block.7.layer.1.EncDecAttention.v.weight', 'decoder.block.7.layer.1.layer_norm.weight', 'decoder.block.7.layer.2.DenseReluDense.wi_0.weight', 'decoder.block.7.layer.2.DenseReluDense.wi_1.weight', 'decoder.block.7.layer.2.DenseReluDense.wo.weight', 'decoder.block.7.layer.2.layer_norm.weight', 'decoder.block.8.layer.0.SelfAttention.k.weight', 'decoder.block.8.layer.0.SelfAttention.o.weight', 'decoder.block.8.layer.0.SelfAttention.q.weight', 'decoder.block.8.layer.0.SelfAttention.v.weight', 'decoder.block.8.layer.0.layer_norm.weight', 'decoder.block.8.layer.1.EncDecAttention.k.weight', 'decoder.block.8.layer.1.EncDecAttention.o.weight', 'decoder.block.8.layer.1.EncDecAttention.q.weight', 'decoder.block.8.layer.1.EncDecAttention.v.weight', 'decoder.block.8.layer.1.layer_norm.weight', 'decoder.block.8.layer.2.DenseReluDense.wi_0.weight', 'decoder.block.8.layer.2.DenseReluDense.wi_1.weight', 'decoder.block.8.layer.2.DenseReluDense.wo.weight', 'decoder.block.8.layer.2.layer_norm.weight', 'decoder.block.9.layer.0.SelfAttention.k.weight', 'decoder.block.9.layer.0.SelfAttention.o.weight', 'decoder.block.9.layer.0.SelfAttention.q.weight', 'decoder.block.9.layer.0.SelfAttention.v.weight', 'decoder.block.9.layer.0.layer_norm.weight', 'decoder.block.9.layer.1.EncDecAttention.k.weight', 'decoder.block.9.layer.1.EncDecAttention.o.weight', 'decoder.block.9.layer.1.EncDecAttention.q.weight', 'decoder.block.9.layer.1.EncDecAttention.v.weight', 'decoder.block.9.layer.1.layer_norm.weight', 'decoder.block.9.layer.2.DenseReluDense.wi_0.weight', 'decoder.block.9.layer.2.DenseReluDense.wi_1.weight', 'decoder.block.9.layer.2.DenseReluDense.wo.weight', 'decoder.block.9.layer.2.layer_norm.weight', 'encoder.block.0.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.0.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.1.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.1.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.10.layer.0.SelfAttention.k.weight', 'encoder.block.10.layer.0.SelfAttention.o.weight', 'encoder.block.10.layer.0.SelfAttention.q.weight', 'encoder.block.10.layer.0.SelfAttention.v.weight', 'encoder.block.10.layer.0.layer_norm.weight', 'encoder.block.10.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.10.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.10.layer.1.DenseReluDense.wo.weight', 'encoder.block.10.layer.1.layer_norm.weight', 'encoder.block.11.layer.0.SelfAttention.k.weight', 'encoder.block.11.layer.0.SelfAttention.o.weight', 'encoder.block.11.layer.0.SelfAttention.q.weight', 'encoder.block.11.layer.0.SelfAttention.v.weight', 'encoder.block.11.layer.0.layer_norm.weight', 'encoder.block.11.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.11.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.11.layer.1.DenseReluDense.wo.weight', 'encoder.block.11.layer.1.layer_norm.weight', 'encoder.block.2.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.2.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.3.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.3.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.4.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.4.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.5.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.5.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.6.layer.0.SelfAttention.k.weight', 'encoder.block.6.layer.0.SelfAttention.o.weight', 'encoder.block.6.layer.0.SelfAttention.q.weight', 'encoder.block.6.layer.0.SelfAttention.v.weight', 'encoder.block.6.layer.0.layer_norm.weight', 'encoder.block.6.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.6.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.6.layer.1.DenseReluDense.wo.weight', 'encoder.block.6.layer.1.layer_norm.weight', 'encoder.block.7.layer.0.SelfAttention.k.weight', 'encoder.block.7.layer.0.SelfAttention.o.weight', 'encoder.block.7.layer.0.SelfAttention.q.weight', 'encoder.block.7.layer.0.SelfAttention.v.weight', 'encoder.block.7.layer.0.layer_norm.weight', 'encoder.block.7.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.7.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.7.layer.1.DenseReluDense.wo.weight', 'encoder.block.7.layer.1.layer_norm.weight', 'encoder.block.8.layer.0.SelfAttention.k.weight', 'encoder.block.8.layer.0.SelfAttention.o.weight', 'encoder.block.8.layer.0.SelfAttention.q.weight', 'encoder.block.8.layer.0.SelfAttention.v.weight', 'encoder.block.8.layer.0.layer_norm.weight', 'encoder.block.8.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.8.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.8.layer.1.DenseReluDense.wo.weight', 'encoder.block.8.layer.1.layer_norm.weight', 'encoder.block.9.layer.0.SelfAttention.k.weight', 'encoder.block.9.layer.0.SelfAttention.o.weight', 'encoder.block.9.layer.0.SelfAttention.q.weight', 'encoder.block.9.layer.0.SelfAttention.v.weight', 'encoder.block.9.layer.0.layer_norm.weight', 'encoder.block.9.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.9.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.9.layer.1.DenseReluDense.wo.weight', 'encoder.block.9.layer.1.layer_norm.weight']
- This IS expected if you are initializing T5ForMultimodalGeneration from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing T5ForMultimodalGeneration from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of T5ForMultimodalGeneration were not initialized from the model checkpoint at JackBAI/webshop-off2on-digirl and are newly initialized: ['decoder.block.0.layer.2.DenseReluDense.wi.weight', 'decoder.block.1.layer.2.DenseReluDense.wi.weight', 'decoder.block.2.layer.2.DenseReluDense.wi.weight', 'decoder.block.3.layer.2.DenseReluDense.wi.weight', 'decoder.block.4.layer.2.DenseReluDense.wi.weight', 'decoder.block.5.layer.2.DenseReluDense.wi.weight', 'encoder.block.0.layer.1.DenseReluDense.wi.weight', 'encoder.block.1.layer.1.DenseReluDense.wi.weight', 'encoder.block.2.layer.1.DenseReluDense.wi.weight', 'encoder.block.3.layer.1.DenseReluDense.wi.weight', 'encoder.block.4.layer.1.DenseReluDense.wi.weight', 'encoder.block.5.layer.1.DenseReluDense.wi.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
```

When I try to perform inference using this model, the output is gibberish, as pointed out in Issue #14. I believe this nonsensical generation output might be linked to the above warnings. Maybe due to a mismatch between the model architecture provided in the code, and the model checkpoint you provide in Huggingface? Would you be able to shed some light on this and explain how best to load your final model checkpoint for inference?

Thank you

**Comment by BiEchi** [comment] 2024-09-09 14:20
It might be a problem with the `config.json` file. I just deleted it on HuggingFace. Would you like to delete the `config.json` file and try things again?

I released two versions of the final checkpoints. The Google Drive version does not have a `config.json` file while the HuggingFace version has it. I did not receive any issues with the GDrive version checkpoint, thus it's probable that deleting `config.json` solves the problem.

**Comment by BiEchi** [comment] 2024-09-09 14:54
By the way, we don't support the `.from_pretrained()` method in huggingface. Please use `trainer.load()` to load the model, as defined in [this file](https://github.com/DigiRL-agent/digirl/blob/master/digirl/algorithms/digirl/trainer.py).

**Comment by StarWalkin** [comment] 2024-09-15 08:17
Hi @BiEchi, thanks for your inspiring work. Currently, I am confused about how to reproduce your results. When I evaluate with AutoUI-base model it went well. But when I downloaded the `JackBAI/general-off2on-digirl` checkpoint from huggingface, changed the "policy model" in `scripts/config/main/default.yaml` to its path and copied the tokenizing and generating configs from AutoUI without other adjustment, I got dimension mismatch when loading the model as mentioned in issue #11.  Doing as suggested in the issue and adding the information to the config.json fixed the size mismatch problem and I managed to load the model, but got untranslatable actions as issue #14  and this issue #16 mention. And if I remove the `config.json` as you say, I will get the `does not appear to have a file named config.json` error with `T5ForMultimodalGeneration.from_pretrained` function.

For us to reproduce the results, could you detail the steps to change the setting and solve all these wierd issues?(Like what to do with the config, and loading method). That would be really helpful. Thanks!

**Comment by BiEchi** [comment] 2024-09-15 11:50
@StarWalkin thanks for following up on this. does the error only occurs if you use the hugging face checkpoint, or does it still occurs when you use the checkpoint in the google drive link?

**Comment by BiEchi** [comment] 2024-09-15 12:06
@StarWalkin Also, the policy model in the `default.yaml` config should still be AutoUI instead of the path to the checkpoint. The path of the checkpoint should be specified in the `save_path` item in `eval_only.yaml`.

**Comment by BiEchi** [comment] 2024-09-15 12:08
Please let me know whether it works, I'll add a patch to README if it works.

**Comment by StarWalkin** [comment] 2024-09-15 12:09
Thanks for your response. Yeah I've seen your previous response and tried downloading the checkpoint in the google drive link. Here is what I exactly did:
- download and unzip `ckpts.zip`
- go to `scripts/config/main/default.yaml` and changed the path of policy_lm: `policy_lm: '/data/home/yguo/models/ckpts/general-off2on-digirl/trainer.pt'`
 
Then I ran the script which worked well for `policy_lm: '/data/home/yguo/models/Auto-UI-Base'` setting, which is `python run.py --config-path config/main --config-name eval_only`, and got the error message:
```
Traceback (most recent call last):
  File "/data/home/yguo/yg/yguo/digirl_original/digirl/scripts/run.py", line 67, in main
    agent = AutoUIAgent(device=device, accelerator=accelerator,
  File "/data/home/yguo/yg/yguo/digirl_original/digirl/digirl/models/autoui_agent.py", line 28, in __init__
    self.model = T5ForMultimodalGeneration.from_pretrained(policy_lm, cache_dir=cache_dir).to(device)
  File "/data/home/yguo/.conda/envs/digirl-origin/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3075, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/data/home/yguo/.conda/envs/digirl-origin/lib/python3.10/site-packages/transformers/configuration_utils.py", line 605, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/data/home/yguo/.conda/envs/digirl-origin/lib/python3.10/site-packages/transformers/configuration_utils.py", line 634, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/data/home/yguo/.conda/envs/digirl-origin/lib/python3.10/site-packages/transformers/configuration_utils.py", line 689, in _get_config_dict
    resolved_config_file = cached_file(
  File "/data/home/yguo/.conda/envs/digirl-origin/lib/python3.10/site-packages/transformers/utils/hub.py", line 356, in cached_file
    raise EnvironmentError(
OSError: /data/home/yguo/models/ckpts/general-off2on-digirl/trainer.pt does not appear to have a file named config.json. Checkout 'https://huggingface.co//data/home/yguo/models/ckpts/general-off2on-digirl/trainer.pt/main' for available files.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

> @StarWalkin Also, the policy model in the `default.yaml` config should still be AutoUI instead of the path to the checkpoint. The path of the checkpoint should be specified in the `save_path` item in `eval_only.yaml`.

**Comment by StarWalkin** [comment] 2024-09-15 13:56
@BiEchi Thanks for ur response. I think some of the people troubled with issue #11, issue #12 and issue #16 may made the same mistake as me. Here is how I worked it out.
- Download the `ckpts.zip` file from google drive and unzip it.
- change `save_path` in `eval_only.yaml` to the path to the checkpoint directory
- go to `scripts` directory and `python run.py --config-path config/main --config-name eval_only`

Currently it's running successfully. I haven't got the final success rate but I think it is the right way for that.

**Comment by BiEchi** [comment] 2024-09-15 15:20
Thanks a lot for confirming! I would also suggest to use the huggingface version to run after you got the success rates using the google drive version. I'll reply to every issue after your confirmation.

**Comment by BiEchi** [comment] 2024-09-18 15:28
Just modified the README. I'll leave this issue open for one more week in case you've got any updates. @StarWalkin

**Comment by BiEchi** [comment] 2024-09-26 04:45
Closing as the problem is now solved.

**Closed as completed by BiEchi** 2024-09-26 04:45 UTC
